Implement outbound frame fragmentation
rsocket/rsocket-swift pull request #18
Opened 2021-02-24 11:58 UTC by nkristek

This PR implements fragmentation for outbound frames.

2021-02-24 14:18 UTC, dnadoba reviewed
Removing `fragmentsFollow` from `*FrameBody` is a welcome change.
As a side effect, this enables us to reduce the memory footprint of some `FrameBody`s, even if it is only a byte. The properties after the flags have stricter memory alignments. In the future, we can reduce the memory footprint by reordering the remaining flags in some `FrameBody`s to the end.

2021-02-24 14:23 UTC, nkristek commented on Sources/RSocketCore/Streams/Fragmentation/Frame+Fragments.swift
> +            guard !fragments.followingFragments.isEmpty else { return [self] }
The guard statement is correctly checking if the followingFragments are empty (the initial frame is not optional by choice), I could however change the return value in the else case to 
```swift
guard !fragments.followingFragments.isEmpty else { return [fragments.initialFragment] }
```

2021-02-24 14:33 UTC, nkristek commented on Sources/RSocketCore/Streams/Fragmentation/Payload+Fragments.swift
> +    ) -> (initialFragment: Payload, followingFragments: [Payload]) {
In this case it actually makes sense to have this form of return tuple, since the first fragment has a different offset (depending on if it's a request frame with `initialRequestN` or not) so the parsing logic is special for the first fragment regardless. 
Thus there wouldn't actually be much of a gain when the return type is an array, it would just introduce ambiguity at the call site.
As you mentioned, the fragmentation should produce one frame at least, so I highly prefer it this way.

2021-02-24 14:35 UTC, nkristek commented on Sources/RSocketCore/Streams/Fragmentation/Frame+Fragments.swift
> +    internal func fragments(mtu: Int32) -> [Frame] {
I like that, although we should keep the naming for MTU since it's a common concept. Would you prefer `splitIntoFragments(mtu:)` or the verbose `splitIntoFragmentsIfNeeded(mtu:)` (I would vote for the latter).

2021-02-24 15:24 UTC, dnadoba commented on Sources/RSocketCore/Streams/Fragmentation/Frame+Fragments.swift
> +    internal func fragments(mtu: Int32) -> [Frame] {
AFAIK, MTU is a term of art used for layer 3 protocols e.g. Internet Protocol.
Because we are way above layer 3, MTU could be confusing.
Network.framework has a[ similar property](https://developer.apple.com/documentation/network/nwconnection/3200451-maximumdatagramsize) and they call it `maximumDatagramSize`. 

I could still live with `splitIntoFragmentsIfNeeded(mtu:)` but we should write some documentation to clarify that we are talking about the maximum frame size in bytes and that the underlying transport overhead is not included.

2021-02-24 15:37 UTC, nkristek commented on Sources/RSocketCore/Streams/Fragmentation/Frame+Fragments.swift
> +    internal func fragments(mtu: Int32) -> [Frame] {
I renamed it to `maximumFrameSize`

2021-02-24 17:41 UTC, dnadoba approved these changes

2021-03-01 13:44 UTC, OlegDokuka requested changes
Looks good with some minor comments

2021-03-01 13:44 UTC, OlegDokuka commented on Sources/RSocketCore/Streams/Defragmentation/FragmentedFrameAssembler.swift
> +                            return .error(reason: "Has fragmentFollows flag without the isNext flag and there is no current set of fragments")
The protocol is explicit about (C)omplete + (F)ollow flags -> https://github.com/rsocket/rsocket/blob/master/Protocol.md#handling-the-unexpected and says that F flag has to simply ignored. 

> A PAYLOAD with both F and C flags set, implicitly ignores the F flag.

The same can be applied for the pure complete frame which has Follows but no Next

2021-03-01 13:44 UTC, OlegDokuka commented on Sources/RSocketCore/Streams/Fragmentation/Frame+SplitIntoFragmentsIfNeeded.swift
> +        return [frame(withStreamId: streamId, additionalFlags: .fragmentFollows)]
I'm fine with that technique but wondering if we should not be lazy in that and read memory chank only when we need that. Or is it already lazy with enumerated support?

2021-03-01 17:23 UTC, dnadoba commented on Sources/RSocketCore/Streams/Fragmentation/Frame+SplitIntoFragmentsIfNeeded.swift
> +        return [frame(withStreamId: streamId, additionalFlags: .fragmentFollows)]
`.enumurated()` is not lazy by default but can be made lazy by adding `.lazy` before `.map(_:)`.
If we want to support lazy fragmentation we would need to add support through out the pipeline. 
As this would only be a performance optimisation for large frames, I would suggest delaying it until we start implementing intelligent enqueuing of frames from different streams.

The algorithm as is can be made lazy quite easily because Swift has built in support for lazy sequences.
The only issue I see is that the types for lazy sequences become very long/nested and we would need to use them trough out the pipeline. 
Opaque Result types (this is the `some` keyword primarily used by SwiftUI) could make this more ergonomic if they ever support constraints on associated types.
Then we could make the result type something like `some T where T: Sequence, T.Element == Frame` and the actual type would just be an implementation detail.
Now we would need to expose the actual type which could look something like `LazyMapSequence<LazySequence<EnumeratedSequence<[Frame]>>.Elements, Frame>` and would change if we  ever change any implementation detail.

2021-03-01 17:25 UTC, OlegDokuka commented on Sources/RSocketCore/Streams/Fragmentation/Frame+SplitIntoFragmentsIfNeeded.swift
> +        return [frame(withStreamId: streamId, additionalFlags: .fragmentFollows)]
> I would suggest delaying it until we start implementing intelligent enqueuing of frames from different streams.

Agree

2021-03-04 08:46 UTC, nkristek commented on Sources/RSocketCore/Streams/Defragmentation/FragmentedFrameAssembler.swift
> +                            return .error(reason: "Has fragmentFollows flag without the isNext flag and there is no current set of fragments")
I removed the corresponding guard checks, good catch!

2021-03-04 16:49 UTC, merged