RSocket protocol instead of one function and one closure to create streams
rsocket/rsocket-swift pull request #19
Opened 2021-02-25 19:10 UTC by dnadoba

### Motivation:
`Requester` and `Responder` should use the same protocol to be more in line with implementations of RSocket in other languages.
This means that `Requester` should provide the `RSocket` interface and `Responder` should be given an object which implements the `RSocket` interface.

### Modifications:

- Unification of `StreamOutput` and `StreamInput` into one type called `RStream` (better name suggestions welcome).
- Use `RStream` instead of `AnyPublisher` and related types in `RSocket`
- Use RSocket instead of `(StreamType, Payload, StreamOutput) -> StreamInput` in Responder
- DemultiplexerHandler conforms now to `RSocket`

### Result:

The API is now much simpler and more in line with other languages.

2021-02-25 21:15 UTC, OlegDokuka commented
Good job, @dnadoba!

I like the direction it goes!

2021-02-25 21:16 UTC, OlegDokuka approved these changes
LGTM

2021-02-25 22:01 UTC, Samer-Abdulaziz approved these changes
looks good thanks @dnadoba

2021-02-26 06:04 UTC, OlegDokuka commented on Sources/RSocketCore/RSocket.swift
> +    func stream(payload: Payload, initialRequestN: Int32, input: RStream) -> RStream
what is the purpose of having channel behavior (e.g. sending stream) in unidirection requestStream interaction?

2021-02-26 08:40 UTC, nkristek requested changes

2021-02-26 08:40 UTC, nkristek commented on Sources/RSocketCore/Streams/Responder.swift
> +    private let responderSocket: RSocket
This means, the responder/requester have a strong reference to the demultiplexer, but the demultiplexer already has a strong reference to both which in turn creates a memory cycle. The closure was using `[weak] self` in order to not fall into this trap. Since there will be one pipeline per client, this will create a memory leak because clients are not cleaned up after.

2021-02-26 08:55 UTC, nkristek approved these changes

2021-02-26 09:36 UTC, dnadoba commented on Sources/RSocketCore/RSocket.swift
> +    func stream(payload: Payload, initialRequestN: Int32, input: RStream) -> RStream
An `RStream` can only send data in one direction. A better name would maybe be something like Simplex (opposite of Duplex according to wikipedia)
Only one `RStream` should send data (e.g. onNext) but both sides can still cancel the stream at any time.

As I think about the semantics, the parameter name `input` is misleading because depending from which side you look at it, either from the Requester or Responder side, each `RStream` is an input for the one and an output for the other.
Maybe we should call it `requesterOutput` or `responderInput` and clarify in the documentation that the `RStream` that is given to `stream(payload:initalRequestN:input)` will receive the messages from the responder and the `RStream` returned can be used to send messages to the responder and the only valid message is a cancel frame.

2021-02-26 11:37 UTC, nkristek commented on Sources/RSocketCore/RSocket.swift
> +    func stream(payload: Payload, initialRequestN: Int32, input: RStream) -> RStream
It's a good idea to limit the interaction a call site can do on some requests, i.e. requestResponse should only be cancelled, so returning a `Cancellable` should be enough. Together with @dnadoba we thought about changing the return types for the methods to:
- RequestFNF: no return value
- RequestResponse: `Cancellable` (allows for sending cancel)
- RequestStream: `Subscription: Cancellable` (allows for sending demand + cancel)
- RequestChannel: `UnidirectionalStream: Subscription` (is equivalent to the `RStream` protocol)

2021-03-04 08:52 UTC, closed without merging