Rsocket protocol
rsocket/rsocket-swift pull request #20
Opened 2021-03-04 17:18 UTC by dnadoba

### Motivation:
`Requester` and `Responder` should use the same protocol to be more in line with implementations of RSocket in other languages.
This means that `Requester` should provide the `RSocket` interface and `Responder` should be given an object which implements the `RSocket` interface.

### Modifications:

- OpenCombine `AnyPublisher`, `SinglePublisher`, `Cancelable`, `Disposable`, etc. is removed
- Use `Cancelable`, `Subscription` and `UnidirectionalStream` instead of `AnyPublisher` and related types in `RSocket`
- Use `RSocket` instead of `(StreamType, Payload, StreamOutput) -> StreamInput` in `Responder`
- Refactor `StreamAdapter` and `StreamFragmenter` into two separate types `RequesterStream` and `ResponderStream` to support new `Cancelable`, `Subscription` and `UnidirectionalStream` instead of `StreamInput` and `StreamOutput`
- add `ThreadSafeStreamAdapter` which converts all stream events (eg. onNext, onCancel, etc,) into frames and forwards them on the right `EventLoop`
- DemultiplexerHandler conforms now to `RSocket`
- implement correct stream termination behaviour 
- move frame fragmentation into `FrameEncoderHandler`

### Result:

The API is now much simpler and more in line with other languages.
streams are terminated i.e. removed from the internal dictionary of active streams
stream events from "clients" are forwarded to the event loop of their corresponding channel

2021-03-05 15:12 UTC, nkristek commented on Sources/RSocketCore/Streams/Responder.swift
> +        let stream = ResponderStream(
Before creating the stream we should check if the initial frame is one of the request frames, otherwise we should drop the frame.

2021-03-05 15:12 UTC, nkristek commented on Sources/RSocketCore/Streams/ResponderStream.swift
> +    }
```suggestion
    private enum State {
        case waitingForInitialFragments(RSocket)
        case active(StreamKind)
    }
```

2021-03-05 15:12 UTC, nkristek commented on Sources/RSocketCore/Streams/TerminationBehaviour.swift
> +
Please adjust whitespace to one line between structs

2021-03-05 15:20 UTC, nkristek commented on Sources/RSocketCore/Streams/Requester.swift
> +    private let eventLoop: EventLoop
Is it safe to get a strong reference to the `EventLoop`? If yes, should we avoid to schedule work with a strong reference to self? E.g. the following will give the event loop a strong reference to self as well:
```swift
eventLoop.execute { [self] in
     let newId = generateNewStreamId()
     send(frame: RequestFireAndForgetFrameBody(payload: payload).frame(withStreamId: newId))
}
```

2021-03-05 17:18 UTC, dnadoba commented on Sources/RSocketCore/Streams/Requester.swift
> +    private let eventLoop: EventLoop
It safe in the sense that it will not create a reference cycle.
Retaining `self` in an execute block will create a temporary reference cycle which will be gone once the submitted block has been executed.

In the case of fireAndForget we could create a weak reference to `self` and only send the frame if the requester is still alive.
In all other cases, we need to set the stream id on the `ThreadSafeStreamAdapter` because some user code could call e.g. `onNext` on the `ThreadSafeStreamAdapter` and this would crash if it did not have a stream id.

I made a diagram which visualises the ownership of each object:
<img width="526" alt="Reference Cycle" src="https://user-images.githubusercontent.com/5688874/110149912-e39f1f00-7dde-11eb-9bc2-ef73602c2bdb.png">
Strong references are solid lines and weak are dashed lines.

2021-03-05 17:28 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/FrameEncoderHandler.swift
> +            context.flush()
Yes, otherwise the data will not be send to the socket.
This is at least suggested by the documentation of [write](https://apple.github.io/swift-nio/docs/current/NIO/Classes/ChannelHandlerContext.html#/s:3NIO21ChannelHandlerContextC5write_7promiseyAA6NIOAnyV_AA16EventLoopPromiseVyytGSgtF)

2021-03-05 17:31 UTC, dnadoba commented on Sources/RSocketCore/Error/Error.swift
> +    internal func asFrame(withStreamId streamId: StreamID) -> Frame {
Sounds good to me but I chose another name because it actually creates a frame from an error and not from a frame body as the other methods do.
Nevertheless, I agree now that they all should be called the same, I will change them all :)

2021-03-05 17:39 UTC, dnadoba commented on Sources/RSocketCore/Streams/Responder.swift
> +        let stream = ResponderStream(
hm... the `ResponderStream` does that after receiving a complete frame.
But we could receive a late fragmented payload or some other malicious frame which then would be stored in memory forever.
I will add a check which only creates a stream if it is one of the request frames. :)

2021-03-10 09:05 UTC, OlegDokuka commented on Sources/RSocketCore/Channel Handler/FrameEncoderHandler.swift
> +            context.flush()
That is how it is done in reactor-netty as of now https://github.com/reactor/reactor-netty/blob/master/reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java#L323

2021-03-10 09:21 UTC, OlegDokuka requested changes
LGTM regardless of a few minor comments

2021-03-10 09:21 UTC, OlegDokuka commented on Sources/RSocketCore/Streams/ThreadSafeStreamAdapter.swift
> +        }
can we do a check if it is already on the eventloop before scheduling something?

```suggestion
        if eventLoop.inEventLoop {
            self.delegate?.send(frame: body.asFrame(withStreamId: self.id))
        } else {
            eventLoop.execute { [self] in
                self.delegate?.send(frame: body.asFrame(withStreamId: self.id))
            }
        } 
```

2021-03-10 09:52 UTC, OlegDokuka commented on Sources/RSocketCore/Streams/ThreadSafeStreamAdapter.swift
> +        }
I guess the block related to streamId generation has to have the same check as in the TreadSafeStreamAdapter. Having both of them check if it is already on the event loop will guarantee serial message sending and ensure that steamId generation happens before the first message being sent. Otherwise, `eventLoop.execute { [self] in` happens always before any other execution and happens before the adapter is given to the user hands

2021-03-10 11:56 UTC, OlegDokuka approved these changes

2021-03-10 11:57 UTC, merged