ReactiveSwift compatibility
rsocket/rsocket-swift pull request #27
Opened 2021-03-11 14:34 UTC by dnadoba

Work in progress with one failing tests
> Note: This PR should be reviewed & merged after #24

2021-03-17 23:21 UTC, nkristek commented on Sources/RSocketReactiveSwift/Responder.swift
> +    }
I think stopping the `SignalProducer` should be enough for now. However, we could expose an optional function on the `RSocket` protocol to receive those errors to log them for example.

2021-03-17 23:23 UTC, nkristek commented on Sources/RSocketReactiveSwift/Responder.swift
> +        // TODO: Not supported by ReactiveSwift. What should we do with it?
As a future improvement (doesn't have to be implemented now), we should make the back pressure behaviour configurable (blocking/queueing/dropping).

2021-03-18 14:09 UTC, nkristek approved these changes

2021-03-19 09:38 UTC, OlegDokuka requested changes
Nice work! However, there are a few unclear points

2021-03-19 09:38 UTC, OlegDokuka commented on Sources/RSocketReactiveSwift/Responder.swift
> +            output.send(event: event)
Should not we add stronger expectations here? if `SinglaProducer` produces more than one signal, it may break the request-response behavior. Also, request-response has a strong relationship between onNext | onError | onComplete. Due to the spec in this interaction type, it can only be one of those signals, where onNext implicitly means onComplete as well

2021-03-19 09:38 UTC, OlegDokuka commented on Tests/RSocketReactiveSwiftTests/RSocketReactiveSwiftTests.swift
> +                observer.sendCompleted()
do we know how many frames this generates?

2021-03-19 09:40 UTC, OlegDokuka commented on Tests/RSocketReactiveSwiftTests/RSocketReactiveSwiftTests.swift
> +                observer.sendCompleted()
can we add a test where the producer produces more than one signal to see if it is canceled right after the first onNext?

2021-03-19 17:59 UTC, dnadoba commented on Tests/RSocketReactiveSwiftTests/RSocketReactiveSwiftTests.swift
> +                observer.sendCompleted()
Good catch! It tried to send two, I have fixed that.

2021-03-19 17:59 UTC, dnadoba commented on Tests/RSocketReactiveSwiftTests/RSocketReactiveSwiftTests.swift
> +                observer.sendCompleted()
I have added a new test: `RSocketReactiveSwiftTests.testRequestResponseWithMisbehavingResponderSignalProducerWhichSendsTwoValuesInsteadOfOne`

2021-03-19 18:00 UTC, dnadoba commented on Sources/RSocketReactiveSwift/Responder.swift
> +            output.send(event: event)
Yes, you are right! I have added an explicit check to only ever send one response.

2021-03-22 08:25 UTC, OlegDokuka approved these changes
LGTM!

2021-03-22 08:26 UTC, merged