Add universal bootstrap client/server API
rsocket/rsocket-swift pull request #28
Opened 2021-03-12 14:56 UTC by nkristek

> Please note: The work on this PR has just started and the client API is not finished.

This PR adds a universal bootstrap for building clients and servers.

2021-03-22 09:03 UTC, OlegDokuka requested changes
left a few comments to clarify

2021-03-22 09:03 UTC, OlegDokuka commented on Tests/RSocketReactiveSwiftTests/RSocketReactiveSwiftTests.swift
> +        client.requester.reactive.metadataPush(metadata: metadata)
I remember, we discussed that this will go away. What is the reason to make things complicated with this extra `reactive` field?

2021-03-22 09:03 UTC, OlegDokuka commented on Sources/RSocketReactiveSwift/Requester.swift
> +    public var reactive: RSocket { RequesterAdapter(requester: self) }
any reasons to keep this?

2021-03-22 16:25 UTC, dnadoba approved these changes

2021-03-23 15:49 UTC, OlegDokuka approved these changes
LGTM

2021-03-23 15:50 UTC, merged