Keep alive connectionstream
rsocket/rsocket-swift pull request #30
Opened 2021-03-18 23:03 UTC by ciychodianda

_[One line description of your change]_

### Motivation:

1. Added KeepAlive support

### Modifications:

1. Added support for starting a background task that sends KeepAlive frames at regular intervals
2. Added support to receive KeepAlive frames
3. Terminate KeepAlive background task if it doesn't hear back before maxLifetime is exceeded
4. Haven't added logic to store lastReceivedPosition

### Result:

1. A connection that is opened must stay up with KeepAlive frames being exchanged between peers

2021-03-22 08:19 UTC, nkristek commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +                let responseKeepAliveFrameBody = KeepAliveFrameBody(respondWithKeepalive: false, lastReceivedPosition: 0, data: Data())
We need to investigate how we could correctly calculate the `lastReceivedPosition`

2021-03-22 08:19 UTC, nkristek commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +                self.keepAliveHandle!.cancel()
```suggestion
                task.cancel()
```

2021-03-22 13:51 UTC, dnadoba requested changes

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +    private var lastReceivedTime = Date()
`Date` should not be used to schedule timers or measure time because it is bound to the system time which is regularly synced and can be changed by the user manually trough the settings app.
I would recommend to use [`ProcessInfo.processInfo.systemUptime`](https://developer.apple.com/documentation/foundation/processinfo/1414553-systemuptime) which [ultimately calls down to mach_absolute_time on Darwin, and clock_gettime with CLOCK_MONOTONIC on Linux.](https://forums.swift.org/t/recommended-way-to-measure-time-in-swift/33326)

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        guard !isKeepAliveStarted, setup.timeBetweenKeepaliveFrames > 0 else { return }
I think this method is called only once from SwiftNIO and `isKeepAliveStarted` is not needed or am I missing something?

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        keepAliveHandle = context.eventLoop.scheduleRepeatedAsyncTask(initialDelay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames)), delay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames
The task should be cancelled in `channelInactive(context:)` or, AFAIK, it will run/repeat forever.

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +                let errorFrame = Frame(header: FrameHeader(streamId: .connection, type: FrameType.error, flags: FrameFlags()), body: FrameBody.error(ErrorFrameBody(error: Error.connectionClose(messag
You can create a `Frame` from an `Error` by just calling `asFrame(withStreamId:)`
```suggestion
                let errorFrame = Error.connectionClose(message: "KeepAlive timeout exceeded").asFrame(withStreamId: .connection)
```

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +                let keepAliveframe = Frame(header: keepAliveFrameBody.header(), body: keepAliveFrameBody.body())
```suggestion
                let keepAliveframe = KeepAliveFrameBody(respondWithKeepalive: true, lastReceivedPosition: 0, data: Data()).asFrame()
```

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/ChannelPipeline.swift
> +        config: ClientSetupConfig,
ClientSetupConfig is not available at this point in time. We need to wait until the client sends `SetupFrameBody` i.e. `initializeConnection` from `ConnectionEstablishmentHandler` is called.

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +    internal init(config: ClientSetupConfig) {
We actually do not need most of `ClientSetupConfig` properties. It would be enough to just initialise `ConnectionStreamHandler` with `timeBetweenKeepaliveFrames` and `maxLifetime`.
In addition, `ClientSetupConfig` is only used on the client. On the server, `SetupInfo` holds the information from the client.

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/ChannelPipeline.swift
> +                    ConnectionStreamHandler(config: config),
The protocol specification says:
> KEEPALIVE frames MAY be initiated by the server and sent upon application request with the (R)espond flag set.

As I understand it, the server should not send `KeepAliveFrame` periodically, but only on user request. 
Is this correct @OlegDokuka?

2021-03-22 13:51 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        if frame.header.type == .keepalive {
An early exit with a guard can improves readability because it makes it clear that the handler only handles keep alive frames and removes one level of indention too.

2021-03-22 14:21 UTC, ciychodianda commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        guard !isKeepAliveStarted, setup.timeBetweenKeepaliveFrames > 0 else { return }
Yup, I removed it in the next version that I'll be pushing.

2021-03-22 14:23 UTC, ciychodianda commented on Sources/RSocketCore/ChannelPipeline.swift
> +                    ConnectionStreamHandler(config: config),
The way it is setup today, both server and client send keepAlive frames. However, I feel server sending keepAlive frames is redundant and can be removed. I kept it this way to keep it similar to other RSocket implementations.

2021-03-22 14:28 UTC, ciychodianda commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        keepAliveHandle = context.eventLoop.scheduleRepeatedAsyncTask(initialDelay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames)), delay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames
Good catch.

2021-03-22 14:41 UTC, ciychodianda commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        keepAliveHandle = context.eventLoop.scheduleRepeatedAsyncTask(initialDelay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames)), delay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames
Here is how I was thinking about cancel

1. Could happen when timeout is exceeded (handled in code now)
2. When app is backgrounded or removed (on exit), all data structures/tasks related to the app will be cleaned up. 

Wouldn't the keepAlive task be cleaned up on (2)?

2021-03-22 14:50 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        keepAliveHandle = context.eventLoop.scheduleRepeatedAsyncTask(initialDelay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames)), delay: .milliseconds(Int64(setup.timeBetweenKeepaliveFrames
[The documentation](https://apple.github.io/swift-nio/docs/current/NIO/Classes/RepeatedTask.html) does not mention anything about automatic cancellation on deallocation.
Looking at the code of `RepeatedTask` and related types, I couldn't find a `deinit` implemantion which does automatic cancellation.

Even if `RepeatedTask` would clean itself up on deallocation, it will never be deallocated because the closure with which `RepatedTask` is initialised, has a strong reference to `self` which creates a reference cycle.

2021-03-26 22:45 UTC, ciychodianda commented
Pushed latest changes. keepAlive will only be started from client end now. In ConnectionStreamHandler(), keepAlive task is started in channelActive() only when the SetupFrame is received in channelRead(). This works currently since ChannelActive() is not called up the chain when some of the intermediate handlers are removed. With this change, I feel we need a check like isKeepAlive started to make sure we don't have duplicate tasks started inadvertently (E.g. if context.fireChannelActive() is propagated up the stack)

One of the performance test is failing on my local machine. It has never run on my local and I see there are few changes in that test recently. I'll hold off on modifications until these changes are merged.

2021-03-29 07:15 UTC, dnadoba commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +        }
keepAliveHandle?.cancel()

2021-03-29 08:46 UTC, dnadoba reviewed
Some edge cases are not handled properly:
- A client sending multiple setup frames
- A server sending a setup frame to the client

As `ConnectionEstablishmentHandler` already has a mechanism of only doing work once a `SetupFrame` has been received, I would suggest initialising `ConnectionStreamHandler` with all data needed. Everything we need is available in `SetupInfo`.

It will also be good to add some tests. 
Testing things like timers can be hard but SwiftNIO has a good `EventLoop` mock ([`EmbeddedEventLoop`](https://apple.github.io/swift-nio/docs/current/NIO/Classes/EmbeddedEventLoop.html)) which allows us to advance time without actually waiting that the time elapses. It's best used in conjunction with [`EmbeddedChannel`](https://apple.github.io/swift-nio/docs/current/NIO/Classes/EmbeddedChannel.html)
The only thing that we need to mock is our notion of "now". This can be done easily buy injecting a function in the initialiser of the handler:
```swift
private let now: () -> TimeInterval
init(now: @escaping () -> TimeInterval) {
    self.now = now
}
```
If you need any help writing tests, let me now :) 

Reviewing was quite hard because there are still changes in this branch which are not really part of your changes. Please merge master into your branch and try to remove commits that are not from this PR so it will be easier for us to review in the future :)

2021-04-01 00:55 UTC, ciychodianda commented
@dnadoba thanks for your help this morning. I made the changes and pushed the latest. I couldn't get the timeout test to work since the channel exits before I can read from it. Could you please take a look at what I might be missing? Thanks.

2021-04-06 10:21 UTC, nkristek commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +    private var maxLifetime: Int32
```suggestion
    private let timeBetweenKeepaliveFrames: Int32
    private let maxLifetime: Int32
```

2021-04-06 10:21 UTC, nkristek commented on Sources/RSocketCore/Channel Handler/ConnectionStreamHandler.swift
> +                let keepAliveFrame = KeepAliveFrameBody(respondWithKeepalive: false, lastReceivedPosition: 0, data: Data()).asFrame()
Let's document it with a comment that `lastReceivedPosition` is set to `0` statically because we don't support resumability yet:
```suggestion
                // we don't support resumability yet so we send always send lastReceivedPosition as 0
                let keepAliveFrame = KeepAliveFrameBody(respondWithKeepalive: false, lastReceivedPosition: 0, data: Data()).asFrame()
```

2021-04-06 13:29 UTC, ciychodianda reviewed
looks good

2021-04-06 14:37 UTC, dnadoba approved these changes

2021-04-07 15:50 UTC, nkristek approved these changes

2021-04-07 16:33 UTC, merged